backend:
  name: github
  repo: erquhart/netlify-cms-test
  site_domain: netlify-cms-test-site.netlify.com
collections:
  - card:
      image: image
      text: title
      type: image
    create: true
    fields:
      - label: Title
        name: title
        tagname: h1
        widget: string
      - format: 'YYYY-MM-DD hh:mma'
        label: Publish Date
        name: date
        widget: datetime
      - label: Cover Image
        name: image
        required: false
        tagname: ''
        widget: image
      - label: Body
        name: body
        widget: markdown
    folder: _posts
    label: Post Has CHANGED
    meta:
      - label: SEO Description
        name: description
        widget: text
    name: posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
  - card:
      text: title
      type: alltype
    create: true
    fields:
      - label: Question
        name: title
        tagname: h1
        widget: string
      - label: Answer
        name: body
        widget: markdown
    folder: _faqs
    label: FAQ
    name: faq
  - editor:
      preview: false
    files:
      - description: CMS Configuration
        fields:
          - fields:
              - label: Name
                name: name
                widget: string
              - label: Repo
                name: repo
                widget: string
            label: Backend
            name: backend
            widget: object
          - fields:
              - label: Name
                name: name
                widget: string
              - label: Label
                name: label
                widget: string
            label: Collections
            name: collections
            widget: list
        file: config.yml
        label: Configuration
        name: config
    label: Settings
    name: settings
media_folder: assets/uploads
